// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC2IbsKhOOsADBT5MruxDPowFtTL7B-3A',
    appId: '1:891263588555:web:ca0b71553d89db9ee7634e',
    messagingSenderId: '891263588555',
    projectId: 'merecharge-50ab0',
    authDomain: 'merecharge-50ab0.firebaseapp.com',
    storageBucket: 'merecharge-50ab0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC2IbsKhOOsADBT5MruxDPowFtTL7B-3A',
    appId: '1:891263588555:android:ca0b71553d89db9ee7634e',
    messagingSenderId: '891263588555',
    projectId: 'merecharge-50ab0',
    storageBucket: 'merecharge-50ab0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC2IbsKhOOsADBT5MruxDPowFtTL7B-3A',
    appId: '1:891263588555:ios:ca0b71553d89db9ee7634e',
    messagingSenderId: '891263588555',
    projectId: 'merecharge-50ab0',
    storageBucket: 'merecharge-50ab0.firebasestorage.app',
    iosBundleId: 'com.meerecharge.blinksoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC2IbsKhOOsADBT5MruxDPowFtTL7B-3A',
    appId: '1:891263588555:macos:ca0b71553d89db9ee7634e',
    messagingSenderId: '891263588555',
    projectId: 'merecharge-50ab0',
    storageBucket: 'merecharge-50ab0.firebasestorage.app',
    iosBundleId: 'com.meerecharge.blinksoft',
  );
}
